### ISSUE TITLE
URBNLin not installing

### ISSUE THREAD

**Issue by jgrandelli** [supermarin/Alcatraz#215]
I know this is no fault of alcatraz, but there doesn't seem to be a wealth of resources around debugging this so I'll ask it here. URBNLin was merged into the packages this morning however when I or anyone else on the team here goes to install via alcatraz, it starts to load (shows the progress) and then stops. Other plugins work. Its also important to note that simply running the plugin project locally does properly install the plugin and it works. Is there something I'm missing?

**Comment by jurre** [comment]
Hey, that's because the name that is specified in the package.json doesn't match the name of the `xcodeproj` in the repository (where it's just called `Lin`). 

This is actually mentioned in the README of the packages repo:

> The url should be a repository containing the Xcode project, and the name should be the same as the .xcodeproj file.

but I should have checked it before merging, apologies!

In short: You'll have to update the name of the `xcodeproj` file and it should work :)

**Comment by jgrandelli** [comment]
Doh! Thats my bad. I fixed it up (I hope) a couple of hours ago. Plugin still isn't installing though. Is there a length of time I should wait? Or do you have to push a button somewhere to make it pick up the new stuff? Thanks for your help!

**Comment by jurre** [comment]
Looks like a little (casing) typo:

`"name": "URBNlin",` `URBNLin.xcodeproj`

I've updated the name in the package list to reflect this and it installs ok for me now :)

**Comment by jgrandelli** [comment]
Thank you, that was dumb. Sorry for the hassle

**Comment by jurre** [comment]
No problem at all!
