### ISSUE TITLE
Xcode 6.2 and GitDiff Plugin issue

### ISSUE THREAD

**Issue by MuscleRumble** [supermarin/Alcatraz#231]
I've already submitted an issue on GitDiff's GitHub (https://github.com/johnno1962/GitDiff/issues/31), but I'll ask here again, because maybe it's an issue with Alcatraz.

I'm getting this alert for GitDiff Plugin on Xcode 6.2:

> Could not load colors interface. This is a problem when using Alcatraz since Xcode6. If problems persist, please download and build from the sources on GitHub.

And Xcode is crashing frequently when installed with GitDiff. So... is there any way to make it work again? Everything was fine with Xcode 6.1.1.

**Comment by johnno1962** [comment]
Hi this more of an Xcode problem since 6.0 than Alcatraz. For some reason when you build a rebuild a project in the background using an NSTask the nib files are not copied into the plugin bundle as it seems to think they are already there. The only solution is to build lmanually from source as suggested.

**Comment by 5amfung** [comment]
@johnno1962 After I git clone the project, then what's next?  Apology for my novice question.  I'm not sure after Product > Build, am I supposed to copy the bundle to somewhere.  More details in README.md would be very appreciated.

**Comment by 5amfung** [comment]
@johnno1962 Never mind it.  Simply building the project seems to install the plugin for me.
