### ISSUE TITLE
Error in terminal

### ISSUE THREAD

**Issue by wh1pch81n** [supermarin/Alcatraz#333]
Hello, I have what looks to be a weird error.  I find it in terminal and I notice it sometimes when I use terminal for terminal tasks.  I do not understand why it mentions Alcatraz on my device.  

[MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs

**Comment by guillaume-algis** [comment]
This is probably shown when you're calling `xcodebuild` (or a script does it for you).
This means that Xcode tries to load the Alcatraz plugin but can't because Alcatraz was not updated to work with your version of Xcode (Alcatraz's plist doesn't include the right UUID). As Alcatraz currently support all recent versions of Xcode, [reinstalling it](https://github.com/supermarin/Alcatraz#installation) should take care of the problem.

Either way, this is just a warning and will not prevent Xcode to work properly.

**Comment by wh1pch81n** [comment]
@guillaume-algis  ok thanks.

**Comment by supermarin** [comment]
You need to update from http://alcatraz.io
